In [225]:
import pandas as pd
import datetime as datetime
import numpy as np
df = pd.read_csv('production_line_optimization_first_log.csv')
df_sanitized = df.drop(df.columns[0], axis=1).drop_duplicates()
df_sorted = df_sanitized.sort_values(by=["line"])

dfArrA = []
dfArrB = []
dfArrC = []
dfArrD = []
for x in range (1,22):
    dfArrA.append(df_sanitized[df_sanitized["job_id"] == x].sort_values(by=["time"]))
for x in range (22,40):
   dfArrB.append(df_sanitized[df_sanitized["job_id"] == x].sort_values(by=["time"]))
for x in range (40,66):
   dfArrC.append(df_sanitized[df_sanitized["job_id"] == x].sort_values(by=["time"]))
for x in range (66,74):
   dfArrD.append(df_sanitized[df_sanitized["job_id"] == x].sort_values(by=["time"]))



In [226]:

dfAllA = pd.concat(dfArrA).sort_values(["time"])

dict = {}
for y in range (1,3):
    module = dfAllA[dfAllA["module"] == y]
    times = []
    job_ids = []
    for x in range (1,22):
        job = module[module["job_id"] == x]
        start = job[job["state"] == "fetching_job"]["time"].values[0]
        end = job[job["state"] == "storing_job"]["time"].values[0]
        job_ids.append(x)
        times.append((datetime.datetime.fromisoformat(end)-datetime.datetime.fromisoformat(start)).total_seconds()*1000)
    dict["job_ids"] = job_ids
    dict["modul"+str(y)+"times"] = times

module = dfAllA[dfAllA["module"] == 3]
times = []
for x in range (1,22):
    if (x < 21):
        job = module[module["job_id"] == x]
        start = job[job["state"] == "fetching_job"]["time"].values[0]
        job = module[module["job_id"] == x+1]
        if (len(job[job["state"] == "waiting_on_precedent"]) > 0):
            end = job[job["state"] == "waiting_on_precedent"]["time"].values[0]
        else:
            end = job[job["state"] == "fetching_job"]["time"].values[0]
        times.append((datetime.datetime.fromisoformat(end)-datetime.datetime.fromisoformat(start)).total_seconds()*1000)
    else :
        job = module[module["job_id"] == x]
        start = job[job["state"] == "fetching_job"]["time"].values[0]
        end = job[job["state"] == "idle"]["time"].values[0]
        times.append((datetime.datetime.fromisoformat(end)-datetime.datetime.fromisoformat(start)).total_seconds()*1000)
dict["modul3times"] = times
print(dict)

pd.DataFrame.from_dict(dict).to_csv("line_a_modultimes.csv")
        

{'job_ids': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21], 'modul1times': [4275245.0, 2143220.6, 1736978.4, 2656078.4, 3175210.0, 2420788.8, 1939180.4, 2729606.4, 2944675.8, 2257189.0, 1569184.2, 3521870.6, 1654259.4, 3233273.2, 4175220.0000000005, 2768208.6, 2596467.6, 3538414.4, 3703852.4000000004, 3225920.4, 2788428.8000000003], 'modul2times': [3591722.199, 2661593.0, 3575178.4, 612000.0, 3360109.0, 3088055.4000000004, 3942818.4, 2740635.6, 3521870.6, 612000.0, 4275532.6, 3668926.5999999996, 2343584.4000000004, 3527385.2, 3538414.4, 3703852.4000000004, 3225920.4, 2788428.8000000003, 3367461.8, 3135848.5999999996, 2713062.6], 'modul3times': [2551300.999, 2341746.2, 2804972.6, 2959381.4000000004, 2159764.4, 612000.0, 2286600.1999999997, 2540271.8, 1793962.6, 4091712.5999999996, 2678136.8000000003, 2538433.5999999996, 2080721.7999999998, 3209376.6, 2547624.6, 2361966.4, 2367481.0, 2895044.4000000004, 612000.0, 2520051.5999999996, 2974087.0]}


In [227]:

dfAllB = pd.concat(dfArrB).sort_values(["time"])

dict = {}
for y in range (1,6):
    module = dfAllB[dfAllB["module"] == y]
    times = []
    job_ids = []
    for x in range (22,40):
        job = module[module["job_id"] == x]
        start = job[job["state"] == "fetching_job"]["time"].values[0]
        end = job[job["state"] == "storing_job"]["time"].values[0]
        job_ids.append(x)
        times.append((datetime.datetime.fromisoformat(end)-datetime.datetime.fromisoformat(start)).total_seconds()*1000)
    dict["job_ids"] = job_ids
    dict["modul"+str(y)+"times"] = times

module = dfAllB[dfAllB["module"] == 3]
times = []
for x in range (22,40):
    if (x < 39):
        job = module[module["job_id"] == x]
        start = job[job["state"] == "fetching_job"]["time"].values[0]
        job = module[module["job_id"] == x+1]
        if (len(job[job["state"] == "waiting_on_precedent"]) > 0):
            end = job[job["state"] == "waiting_on_precedent"]["time"].values[0]
        else:
            end = job[job["state"] == "fetching_job"]["time"].values[0]
        times.append((datetime.datetime.fromisoformat(end)-datetime.datetime.fromisoformat(start)).total_seconds()*1000)
    else :
        job = module[module["job_id"] == x]
        start = job[job["state"] == "fetching_job"]["time"].values[0]
        end = job[job["state"] == "idle"]["time"].values[0]
        times.append((datetime.datetime.fromisoformat(end)-datetime.datetime.fromisoformat(start)).total_seconds()*1000)
dict["modul6times"] = times
print(dict)

pd.DataFrame.from_dict(dict).to_csv("line_b_modultimes.csv")

{'job_ids': [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39], 'modul1times': [1276659.5999999999, 1499081.7999999998, 1576286.1989999998, 1225190.001, 1539522.2000000002, 2019292.4000000001, 2486135.8, 3122212.4, 2738028.6, 2804203.8, 2710455.5999999996, 2568914.2, 1774811.8, 3616688.199, 2041350.8, 1931058.8, 3135447.44, 3036184.64], 'modul2times': [3318899.8000000003, 2186568.6, 2221494.4, 2618545.6, 3122212.399, 2738028.601, 2804203.8, 2710455.5999999996, 2568914.2, 1774811.8, 3616688.199, 2041350.8, 398000.0, 2519282.801, 2826262.1989999996, 2449431.2, 4417040.481, 398000.0], 'modul3times': [2420020.0, 398000.0, 2142451.8, 398000.0, 2300537.001, 398000.0, 1666358.0, 1670034.4, 1964146.4000000001, 1522978.4, 1653490.6, 1594668.2000000002, 2177377.5999999996, 1991719.401, 2135099.0, 398000.0, 3292062.08, 3845727.92], 'modul4times': [2164510.2, 2267449.4, 3096477.6, 4993500.0, 2022968.8, 2392447.0, 2692073.6, 2848320.6, 2828100.4, 2190245.0, 1953117.2, 2559723.

In [228]:

dfAllC = pd.concat(dfArrC).sort_values(["time"])

dict = {}
for y in range (1,7):
    module = dfAllC[dfAllC["module"] == y]
    times = []
    job_ids = []
    for x in range (40,66):
        job = module[module["job_id"] == x]
        start = job[job["state"] == "fetching_job"]["time"].values[0]
        end = job[job["state"] == "storing_job"]["time"].values[0]
        job_ids.append(x)
        times.append((datetime.datetime.fromisoformat(end)-datetime.datetime.fromisoformat(start)).total_seconds()*1000)
    dict["job_ids"] = job_ids
    dict["modul"+str(y)+"times"] = times

module = dfAllC[dfAllC["module"] == 3]
times = []
for x in range (40,66):
    if (x < 65):
        job = module[module["job_id"] == x]
        start = job[job["state"] == "fetching_job"]["time"].values[0]
        job = module[module["job_id"] == x+1]
        if (len(job[job["state"] == "waiting_on_precedent"]) > 0):
            end = job[job["state"] == "waiting_on_precedent"]["time"].values[0]
        else:
            end = job[job["state"] == "fetching_job"]["time"].values[0]
        times.append((datetime.datetime.fromisoformat(end)-datetime.datetime.fromisoformat(start)).total_seconds()*1000)
    else :
        job = module[module["job_id"] == x]
        start = job[job["state"] == "fetching_job"]["time"].values[0]
        end = job[job["state"] == "idle"]["time"].values[0]
        times.append((datetime.datetime.fromisoformat(end)-datetime.datetime.fromisoformat(start)).total_seconds()*1000)
dict["modul7times"] = times
print(dict)

pd.DataFrame.from_dict(dict).to_csv("line_c_modultimes.csv")

{'job_ids': [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65], 'modul1times': [1773740.8, 1504326.2, 1649762.4000000001, 1282595.6, 286000.0, 934502.399, 1318358.6, 286000.0, 1022717.8, 286000.0, 1344584.801, 5652834.2, 286000.0, 1370811.0, 1292132.4, 286000.0, 1346969.0, 1304053.4, 1110933.2, 965497.0, 1408958.2, 805755.6, 286000.0, 1139543.5990000002, 1344584.8, 1382732.0010000002], 'modul2times': [286000.0, 286000.0, 286000.0, 286000.0, 1299285.0, 286000.0, 286000.0, 1211069.6, 286000.0, 286000.0, 1239680.0, 1349353.2, 1187227.5999999999, 286000.0, 286000.0, 1027486.2000000001, 927349.7999999999, 286000.0, 286000.0, 1196764.4, 286000.0, 286000.0, 286000.0, 286000.0, 286000.0, 286000.0], 'modul3times': [286000.0, 286000.0, 286000.0, 1311206.0, 1442336.999, 286000.0, 286000.0, 286000.0, 1130006.8, 2732605.201, 286000.0, 1146696.2000000002, 1103780.6, 286000.0, 286000.0, 286000.0, 286000.0, 1213453.8, 1153848.8, 1346969.0, 812908.2

In [229]:

dfAllD = pd.concat(dfArrD).sort_values(["time"])

dict = {}
for y in range (1,4):
    module = dfAllD[dfAllD["module"] == y]
    times = []
    job_ids = []
    for x in range (66,74):
        job = module[module["job_id"] == x]
        start = job[job["state"] == "fetching_job"]["time"].values[0]
        end = job[job["state"] == "storing_job"]["time"].values[0]
        job_ids.append(x)
        times.append((datetime.datetime.fromisoformat(end)-datetime.datetime.fromisoformat(start)).total_seconds()*1000)
    dict["job_ids"] = job_ids
    dict["modul"+str(y)+"times"] = times

module = dfAllD[dfAllD["module"] == 3]
times = []
for x in range (66,74):
    if (x < 73):
        job = module[module["job_id"] == x]
        start = job[job["state"] == "fetching_job"]["time"].values[0]
        job = module[module["job_id"] == x+1]
        if (len(job[job["state"] == "waiting_on_precedent"]) > 0):
            end = job[job["state"] == "waiting_on_precedent"]["time"].values[0]
        else:
            end = job[job["state"] == "fetching_job"]["time"].values[0]
        times.append((datetime.datetime.fromisoformat(end)-datetime.datetime.fromisoformat(start)).total_seconds()*1000)
    else :
        job = module[module["job_id"] == x]
        start = job[job["state"] == "fetching_job"]["time"].values[0]
        end = job[job["state"] == "idle"]["time"].values[0]
        times.append((datetime.datetime.fromisoformat(end)-datetime.datetime.fromisoformat(start)).total_seconds()*1000)
dict["modul4times"] = times
print(dict)

pd.DataFrame.from_dict(dict).to_csv("line_d_modultimes.csv")

{'job_ids': [66, 67, 68, 69, 70, 71, 72, 73], 'modul1times': [974865.0, 1184674.6, 962944.0, 1729550.0, 729292.4, 1220437.5999999999, 822276.2000000001, 1170369.4000000001], 'modul2times': [1125069.6, 688761.0, 936717.8, 960559.8, 1039238.3999999999, 924796.7999999999, 1141759.0, 1036854.2], 'modul3times': [1685356.599, 1823640.199, 1077385.6, 1406405.2, 1785493.0, 1272890.0, 6215336.6, 1194211.4], 'modul4times': [1885356.6, 2023640.199, 1277385.6, 1606405.2, 1985493.0, 1472890.0, 6415336.6, 1394211.4]}


In [241]:
df = pd.read_csv("line_a_modultimes.csv")
df
df["sum"] = df.iloc[:, 2:].sum(axis=1)
df["mean"] = df.iloc[:, 2:].mean(axis=1)
df = df.sort_values(by=["sum"], ascending=False)
jobIds = np.array(df["job_ids"])
jobIds

array([ 1, 15, 14, 12, 18, 20, 16,  5, 11, 21,  9, 17,  7,  3,  8, 19,  2,
       10,  4,  6, 13], dtype=int64)

In [242]:
df = pd.read_csv("line_b_modultimes.csv")
df["sum"] = df.iloc[:, 2:].sum(axis=1)
df["mean"] = df.iloc[:, 2:].mean(axis=1)
df = df.sort_values(by=["sum"], ascending=False)
jobIds = np.array(df["job_ids"])
jobIds

array([38, 39, 35, 24, 22, 30, 28, 26, 36, 33, 31, 29, 32, 25, 37, 34, 27,
       23], dtype=int64)

In [243]:
df = pd.read_csv("line_c_modultimes.csv")
df["sum"] = df.iloc[:, 2:].sum(axis=1)
df["mean"] = df.iloc[:, 2:].mean(axis=1)
df = df.sort_values(by=["sum"], ascending=False)
jobIds = np.array(df["job_ids"])
jobIds

array([43, 51, 49, 59, 46, 56, 63, 64, 57, 60, 50, 58, 52, 44, 48, 65, 61,
       62, 54, 53, 55, 47, 40, 42, 41, 45], dtype=int64)

In [233]:
df = pd.read_csv("line_d_modultimes.csv")
df["sum"] = df.iloc[:, 2:].sum(axis=1)
df["mean"] = df.iloc[:, 2:].mean(axis=1)
df = df.sort_values(by=["sum"], ascending=False)
jobIds = np.array(df["job_ids"])
jobIds

array([68, 73, 71, 70, 66, 69, 67, 72], dtype=int64)